### ISSUE TITLE
Typo "invalid"

### ISSUE THREAD

**Issue by stakery** [nearprotocol/nearlib#105]
![Typo](https://i.imgur.com/VC9lQtE.png)

**Comment by vgrichina** [comment]
This is fixed as drive-by in https://github.com/nearprotocol/nearlib/pull/109/files

Next time you find anything like this – feel free to edit `.ts` file directly on GitHub and submit a PR (should be possible to do through web UI). All `.js` files outside of `test/` are auto-generated, so no need to update them (they'll be updated anyway when cutting new npm release, etc).
