### ISSUE TITLE
misleading error message from Signer

### ISSUE THREAD

**Issue by amgando** [nearprotocol/nearlib#111]
the error message reported in the snippet below would be clearer to me if it read "Missing *private* key ..." since the signer is failing to fetch a private key from the keystore with `signer.getPublicKey`
https://github.com/nearprotocol/nearlib/blob/d8b0f397fdf6a0729d293660e3c4dda153ea314e/src.ts/account.ts#L56-L60

is this because i'm still confused about how keys work?  it's possible 😕 

or maybe is "Missing public key ..." somehow the canonical way to report that "a private key was not found locally and so no associated public key could be retrieved" or something?

**Comment by vgrichina** [comment]
I think it should be removed altogether, as is not really an error at all. Error should be reported on transaction signing attempt instead.
