### ISSUE TITLE
bs58 should be smarter

### ISSUE THREAD

**Issue by vans163** [nearprotocol/nearlib#12]
```
    /**
     * Encode a buffer as string using bs58
     * @param {Buffer} buffer 
     * @example
     * KeyPair.encodeBufferInBs58(key.publicKey)
     */
    static encodeBufferInBs58(buffer) {
        const bytes = Buffer.from(buffer);
        const encodedValue = bs58.encode(bytes);
        return encodedValue;
    }
```
Stuff like this should be inside the bs58.encode() function instead of outside, bs58 should auto determine the type is Buffer or Uint8Array.  Maybe use a forked bs58 with this update?

Or get a base58 lib that supports uint8array buffers.

**Comment by vgrichina** [comment]
@vans163 there is no node.js buffers on WASM/AssemblyScript side.

**Comment by vans163** [comment]
Yea neither is there inbrowser, it gets transcompiled to other functions.

**Comment by bowenwang1996** [comment]
I think we are moving to base64 encoding so this will be deprecated in the future. https://github.com/nearprotocol/nearcore/pull/946

**Comment by ilblackdragon** [comment]
Actually kept bs58, as it's way more readable / urlable.
Abstracted usage of the library & only have conversion for string:
https://github.com/nearprotocol/nearlib/pull/41/files#diff-197142a49f3ee5844a76c5305b04eb24R1

**Comment by vans163** [comment]
This can be closed then? nearlib now has generic base58 ser/deser? (that works with both nodejs buffers and uint8arrays?
