### ISSUE TITLE
misspelling nit in developer-facing error message

### ISSUE THREAD

**Issue by amgando** [nearprotocol/nearlib#122]
_Quering_ `${path} failed` should be **Querying** `${path} failed`

https://github.com/nearprotocol/nearlib/blob/d8b0f397fdf6a0729d293660e3c4dda153ea314e/src.ts/providers/json-rpc-provider.ts#L53-L59

**Comment by vgrichina** [comment]
Please just submit PR for such issues (or even edit `master` directly). It's possible to edit the file right in GH interface.

**Comment by amgando** [comment]
will edit via GH interface directly
