### ISSUE TITLE
separate construction and signing of transactions

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearlib#167]
We should consider separating construction and signing of transactions so that unsigned transactions can be passed to signers not on the same device for example.

**Comment by kcole16** [comment]
@vgrichina Is this currently possible in nearlib?

**Comment by bowenwang1996** [comment]
I have a PR https://github.com/nearprotocol/nearlib/pull/184 but is not backward compatible. The problems is that I don't know what's a good name for the function that signs the transaction since we already have `signTransaction` if we would like to be backward compatible.

**Comment by vgrichina** [comment]
@kcole16 this is tested and merged now.
