### ISSUE TITLE
Using Date.now() as nonce in signAndSendTransaction

### ISSUE THREAD

**Issue by StardustCrypto** [nearprotocol/nearlib#190]
Seems like a good solution to avoid nonce collisions, proposed by @ilblackdragon 

https://github.com/nearprotocol/nearlib/blob/master/lib/account.js#L66

@vgrichina thoughts?

@DanielRX 

This **is needed ASAP**. So please prioritize this

**Comment by vgrichina** [comment]
@StardustCrypto @DanielRX generally this is already achievable:

1) Create transaction manually with any desired nonce:
https://github.com/nearprotocol/nearlib/blob/1ddc03a2d5bc18c826616022597daad5f71b41a3/src.ts/account.ts#L96-L98

2) Send transaction using `provider` directly:
https://github.com/nearprotocol/nearlib/blob/master/src.ts/account.ts#L102

So I'm not sure what is a blocker on our side. Is this the common logs/error handling stuff? 
https://github.com/nearprotocol/nearlib/blob/1ddc03a2d5bc18c826616022597daad5f71b41a3/src.ts/account.ts#L111-L123
