### ISSUE TITLE
ActionErrorKind::FunctionCallError gets mapped into wrong error

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearlib#210]
Returning `ActionErrorKind::FunctionCallError` from NEAR Core, shows error `The used access key requires exactly one FunctionCall action` in nearlib/nearcore instead of underlying error.

**Comment by ilblackdragon** [comment]
@fckt also the arguments from ActionError seemed to be lost as well.

**Comment by fckt** [comment]
Could be it any chance that @ilblackdragon was using an outdated nearlib with a newest nearcore?

**Comment by fckt** [comment]
might be related https://github.com/nearprotocol/nearlib/issues/206

**Comment by evgenykuzyakov** [comment]
It's possible that there are `nearcore` version doesn't match schema. But I think current nearlib schema is the same as staging `nearcore` schema.
